version: "3"

services:
  redis:
    image: redis

  cli:
    image: ${CPYTHON_CLI_IMAGE}
    volumes:
        - .:/code/faasm-cpython
    working_dir: /code/faasm-cpython
    stdin_open: true
    tty: true
    privileged: true
    environment:
      - LOG_LEVEL=debug
      - REDIS_STATE_HOST=redis
      - REDIS_QUEUE_HOST=redis
    depends_on:
      - redis
